### ISSUE TITLE
No network and cursor is frozen!

### ISSUE THREAD

**Issue by j75** [farabimahmud/emulate-raspberry-pi3-in-qemu#1]
Hello,

I am on Ubuntu 22.04 and when running the **launch.sh** script I noticed two problems:
- no internet! (in the terminal where I connect as user "pi" there's only the **lo** interface),
- in the graphical window the cursor is locked and everything there seems to be frozen!

Any idea of how to overcome these problems?

**Comment by j75** [comment]
Well, I managed to have Internet by using the Debian Bullseye image (from https://www.raspberrypi.com/software/operating-systems/ Raspberry Pi OS with desktop 64 bits) but now the graphical window is completely black... :-(
```
 eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.0.2.15  netmask 255.255.255.0  broadcast 10.0.2.255
        inet6 fec0::55c0:f627:9e51:c4b  prefixlen 64  scopeid 0x40<site>
        inet6 fe80::22d6:91fa:eaee:a9b6  prefixlen 64  scopeid 0x20<link>
        ether 40:54:00:12:34:57  txqueuelen 1000  (Ethernet)
        RX packets 13  bytes 4516 (4.4 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 42  bytes 4908 (4.7 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

**Comment by ivon852** [comment]
@j75 You have to use the correct kernel to boot the VM.

Follow [this guide](https://github.com/dhruvvyas90/qemu-rpi-kernel/tree/master/native-emulation) to extract kernel and dtbs from the latest Bullseye image (64bit).
